#!/usr/bin/env python3
"""
BDF → BitmapFont C array converter (Plan 71).

Converts u8g2 BDF font sources to Palanu BitmapFont format.
Input:  BDF file (text, human-readable bitmap font definition).
Output: C++ file with const BitmapFont + glyph data array.

BDF BITMAP layout: row-major hex, row 0 = top, bit 7 = leftmost pixel.
Palanu BitmapFont:   column-major bytes, bit 0 = topmost pixel in column.

Usage:
  python encode.py sources/u8g2_font_helvB08_tf.bdf output/font_primary.cpp FontPrimary primary
"""

import sys
import os
import re
from collections import OrderedDict

HEADER = """// Generated by tools/fonts/encode.py (Plan 71) — do not edit.
// Source: {}
#include "nema/ui/canvas.h"

namespace nema {{

static const uint8_t {}_DATA[] = {{
"""

FOOTER = """}};

const BitmapFont {0} = {{
    {1}_DATA,
    {2},    // charW
    {3},    // charH
    0x{4:02X}, // firstChar
    {5},     // numChars
    {6},     // spacing
}};

}} // namespace nema
"""


def parse_bdf(path):
    """Parse BDF file, return list of (codepoint, width, height, pixels_2d).

    pixels_2d is a list of rows, each row is a list of bools (True = set).
    """
    with open(path, 'r', encoding='latin-1', errors='replace') as f:
        lines = f.readlines()

    glyphs = OrderedDict()
    in_char = False
    in_bitmap = False
    codepoint = None
    bbx_w = bbx_h = bbx_x = bbx_y = 0
    bitmap_rows = []
    num_chars = 0
    global_bbx = None

    for line in lines:
        line = line.strip()

        # Global bounding box
        if line.startswith('FONTBOUNDINGBOX'):
            parts = line.split()
            global_bbx = (int(parts[1]), int(parts[2]),
                          int(parts[3]), int(parts[4]))

        if line.startswith('CHARS '):
            num_chars = int(line.split()[1])
            continue

        if line.startswith('STARTCHAR'):
            in_char = True
            bitmap_rows = []
            continue

        if not in_char:
            continue

        if line.startswith('ENCODING '):
            codepoint = int(line.split()[1])
            continue

        if line.startswith('BBX '):
            parts = line.split()
            bbx_w = int(parts[1])
            bbx_h = int(parts[2])
            bbx_x = int(parts[3])
            bbx_y = int(parts[4])
            continue

        if line == 'BITMAP':
            in_bitmap = True
            continue

        if line == 'ENDCHAR':
            in_char = False
            in_bitmap = False
            if codepoint is not None and bbx_w > 0 and bbx_h > 0:
                # Convert hex rows → 2D pixel array.
                # For wide glyphs (>8px), each BITMAP row has multiple hex bytes
                # (ceil(bbx_w/8) bytes). Concatenate bits from all bytes.
                byte_width = max(1, (bbx_w + 7) // 8)
                pixels = []
                for row_hex in bitmap_rows:
                    row_pixels = []
                    # Read byte_width hex bytes from this row
                    for bi in range(byte_width):
                        # Get the i-th byte from the hex string
                        byte_str = row_hex[bi * 2 : bi * 2 + 2]
                        val = int(byte_str, 16) if byte_str else 0
                        # Process bits within this byte
                        for col_offset in range(8):
                            col = bi * 8 + col_offset
                            if col >= bbx_w:
                                break
                            bit = (val >> (7 - col_offset)) & 1
                            row_pixels.append(bool(bit))
                    pixels.append(row_pixels)
                glyphs[codepoint] = {
                    'w': bbx_w,
                    'h': bbx_h,
                    'pixels': pixels,
                }
            bitmap_rows = []
            continue

        if in_bitmap and line:
            bitmap_rows.append(line)

    return glyphs, global_bbx


def row_to_col(pixels, glyph_w, glyph_h, char_w, char_h):
    """Convert row-major pixels → column-major bytes.

    pixels: list of rows, each row = list of bools
    Output: list of char_w bytes (one per column), padded to char_w × char_h.
    Within each byte: bit 0 = topmost row (aka LSB = top).
    """
    cols = []

    for col in range(char_w):
        byte_val = 0
        for row in range(char_h):
            # Determine if pixel at (col, row) is set
            on = False
            if col < glyph_w and row < glyph_h:
                on = pixels[row][col]

            if on:
                # bit 0 = row 0 (top). Add 1 << row if within 8 bits.
                if row < 8:
                    byte_val |= (1 << row)
                # If char_h > 8, we'd need multi-byte columns, but v1
                # fonts are all <= 8 pixels tall, so one byte per column.
        cols.append(byte_val)

    return cols


def encode_font(source_path, glyphs, char_w, char_h, first_char, spacing):
    """Encode all glyphs into a byte array string (C initializer)."""
    # Filter to ASCII range we support (0x20..0x7E)
    ascii_start = max(0x20, first_char)
    ascii_end = min(0x7E, first_char + 95)

    lines = []
    bytes_per_glyph = char_w
    count = 0

    for cp in range(ascii_start, ascii_end + 1):
        glyph = glyphs.get(cp)
        if glyph and glyph['w'] > 0 and glyph['h'] > 0:
            cols = row_to_col(glyph['pixels'], glyph['w'], glyph['h'],
                              char_w, char_h)
        else:
            # Missing glyph → empty bytes
            cols = [0] * char_w

        # Format as C hex bytes
        hex_str = ','.join(f'0x{b:02X}' for b in cols)
        lines.append(f"    {hex_str}, // 0x{cp:02X} '{chr(cp) if 32 <= cp < 127 else '?'}'")
        count += 1

    data_name = os.path.splitext(os.path.basename(source_path))[0]
    return '\n'.join(lines), count, data_name


def main():
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <input.bdf> <output.cpp> <FontName> "
              "[charW] [charH] [firstChar] [spacing]")
        sys.exit(1)

    source = sys.argv[1]
    output = sys.argv[2]
    font_name = sys.argv[3]

    glyphs, global_bbx = parse_bdf(source)

    if not glyphs:
        print(f"Error: no glyphs found in {source}")
        sys.exit(1)

    # Determine charW/charH from arguments or auto-detect
    if len(sys.argv) >= 5:
        char_w = int(sys.argv[4])
    else:
        char_w = max(g['w'] for g in glyphs.values())

    if len(sys.argv) >= 6:
        char_h = int(sys.argv[5])
    else:
        char_h = max(g['h'] for g in glyphs.values())

    first_char = int(sys.argv[6], 0) if len(sys.argv) >= 7 else 0x20
    spacing = int(sys.argv[7]) if len(sys.argv) >= 8 else 1

    # Ensure charW and charH are reasonable
    if char_w < 1 or char_w > 64:
        char_w = 5
    if char_h < 1 or char_h > 16:
        char_h = 8

    data_lines, num_chars, _ = encode_font(source, glyphs, char_w, char_h,
                                            first_char, spacing)

    # Build output variable name from font name
    data_name = font_name.upper()

    with open(output, 'w') as f:
        f.write(HEADER.format(
            os.path.basename(source),
            data_name
        ))

        f.write(data_lines)
        f.write('\n')
        f.write(FOOTER.format(
            font_name,
            data_name,
            char_w,
            char_h,
            first_char,
            num_chars,
            spacing
        ))

    print(f"Generated {output}: {char_w}x{char_h}, {num_chars} glyphs "
          f"({num_chars * char_w} bytes)")


if __name__ == '__main__':
    main()
