#!/usr/bin/env python3
"""
Generate a C++ pack header from a directory of .bmf files.

Usage:
  python3 gen_pack_header.py <bmf_dir> <CamelPrefix> <kPrefix> <out.h>

Example:
  python3 gen_pack_header.py \
    packs/IBMPlexMono \
    IbmPlexMono kIbmPlexMono \
    ../../firmware/core/include/nema/assets/fonts/ibm_plex_mono_pack.h

Looks for: reg8.bmf  bold8.bmf  reg10.bmf  bold10.bmf  reg12.bmf  bold12.bmf
Produces a header with one static const uint8_t array per file and a matching _Len constant.
"""

import sys
import os

SIZES = ["reg8", "bold8", "reg10", "bold10", "reg12", "bold12"]

def camel_to_arr(k_prefix, size):
    # e.g. kIbmPlexMono + Reg8 → kIbmPlexMonoReg8
    return k_prefix + size[0].upper() + size[1:]

def main():
    if len(sys.argv) != 5:
        print(__doc__)
        sys.exit(1)

    bmf_dir, camel_prefix, k_prefix, out_path = sys.argv[1:]

    lines = [
        "#pragma once",
        "// Auto-generated by tools/fonts/gen_pack_header.py — do not edit.",
        "#include <stddef.h>",
        "",
    ]

    for size in SIZES:
        path = os.path.join(bmf_dir, f"{size}.bmf")
        if not os.path.exists(path):
            print(f"Warning: {path} not found, skipping {size}", file=sys.stderr)
            continue

        data = open(path, "rb").read()
        arr_name = camel_to_arr(k_prefix, size)

        lines.append(f"// {size}")
        lines.append(f"static const uint8_t {arr_name}[] = {{")

        cols = []
        for i, b in enumerate(data):
            cols.append(f"0x{b:02X}")
        # 16 bytes per line
        for i in range(0, len(cols), 16):
            chunk = cols[i:i+16]
            lines.append("    " + ", ".join(chunk) + ",")

        lines.append("};")
        lines.append(f"static const size_t {arr_name}Len = sizeof({arr_name});")
        lines.append("")

    out = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(out)
    print(f"Written: {out_path}")

if __name__ == "__main__":
    main()
