#!/usr/bin/env python3
"""
TTF → BitmapFont C array converter (Palanu / Plan 79).

Uses Pillow (PIL) to render each ASCII glyph at a specified pixel size,
then encodes the result in the column-major BitmapFont format used by the
firmware (same layout as encode.py but starting from a TTF instead of BDF).

For monospace fonts every glyph gets the same advance width; for proportional
fonts per-glyph advance widths are measured.

Usage:
  python3 ttf_encode.py Regular.ttf 10 font_iosk_reg10.cpp FONT_IOSK_REG10 iosk_reg10 [spacing] [--prop] [--bmf]

  --prop  Write C array output (default if neither flag given)
  --bmf   Write binary .bmf output (same base path, .bmf extension)
  Both flags may be combined to write both outputs.
"""

import sys
import os
import struct
from PIL import ImageFont

ASCII_FIRST = 0x20
ASCII_LAST  = 0x7E

HEADER = (
    "// Generated by tools/fonts/ttf_encode.py — do not edit.\n"
    "// Source: {src}  size: {sz}px\n"
    "#include \"nema/ui/canvas.h\"\n\n"
    "namespace nema::display {{\n\n"
)


def render_glyph(font, ch, cell_h, ascent):
    """Render a single character; return list of `advance` columns,
    each a list of `cell_h` bools (True = pixel set).
    Uses FreeType mode='1' (true monochrome hinting) so strokes snap
    cleanly to the pixel grid without antialiasing artifacts."""
    advance = max(1, round(font.getlength(ch)))
    bbox = font.getbbox(ch)           # (l, top, r, bottom) from cell origin
    top = bbox[1] if bbox else 0

    # getmask with mode='1' uses FreeType's monochrome renderer — each pixel
    # is fully on or off, stroke widths are consistent.
    mask = font.getmask(ch, mode='1')
    mw, mh = mask.size

    cols = []
    for x in range(advance):
        col = [False] * cell_h
        for y in range(mh):
            dst_y = top + y
            if 0 <= dst_y < cell_h and x < mw:
                col[dst_y] = bool(mask.getpixel((x, y)))
        cols.append(col)
    return cols, advance


def encode_columns(cols, bytes_per_col):
    """Encode column list → flat byte list (bit 0 = topmost row)."""
    out = []
    for col in cols:
        for b in range(bytes_per_col):
            v = 0
            for bit in range(8):
                row = b * 8 + bit
                if row < len(col) and col[row]:
                    v |= (1 << bit)
            out.append(v)
    return out


def collect_font_data(ttf_path, px_size, spacing=1):
    """Render all glyphs and return (font_metrics_dict, widths, offsets, data_bytes)."""
    font = ImageFont.truetype(ttf_path, px_size)
    ascent, descent = font.getmetrics()
    cell_h = ascent + abs(descent)
    bytes_per_col = 2 if cell_h > 8 else 1

    chars = [chr(cp) for cp in range(ASCII_FIRST, ASCII_LAST + 1)]

    data_bytes = []
    widths  = []
    offsets = []

    for ch in chars:
        cols, advance = render_glyph(font, ch, cell_h, ascent)
        offsets.append(len(data_bytes))
        widths.append(advance)
        data_bytes.extend(encode_columns(cols, bytes_per_col))

    num   = len(chars)
    max_w = max(widths)

    metrics = {
        'cell_h': cell_h,
        'bytes_per_col': bytes_per_col,
        'num': num,
        'max_w': max_w,
        'spacing': spacing,
        'ttf_path': ttf_path,
        'px_size': px_size,
    }
    return metrics, widths, offsets, data_bytes


def emit_proportional(out_path, font_var, data_prefix, metrics, widths, offsets, data_bytes):
    """Write C array output (.cpp file)."""
    cell_h       = metrics['cell_h']
    bytes_per_col = metrics['bytes_per_col']
    num          = metrics['num']
    max_w        = metrics['max_w']
    spacing      = metrics['spacing']
    ttf_path     = metrics['ttf_path']
    px_size      = metrics['px_size']
    data_nm      = data_prefix.upper()

    def hexrow(vals):
        return ','.join(f'0x{v:02X}' for v in vals)

    with open(out_path, 'w') as f:
        f.write(HEADER.format(src=os.path.basename(ttf_path), sz=px_size))

        f.write(f'static const uint8_t {data_nm}_DATA[] = {{\n')
        for i in range(0, len(data_bytes), 16):
            f.write('    ' + hexrow(data_bytes[i:i+16]) + ',\n')
        f.write('};\n\n')

        f.write(f'static const uint8_t {data_nm}_W[] = {{\n')
        for i in range(0, num, 24):
            f.write('    ' + ','.join(str(v) for v in widths[i:i+24]) + ',\n')
        f.write('};\n\n')

        f.write(f'static const uint16_t {data_nm}_OFF[] = {{\n')
        for i in range(0, num, 16):
            f.write('    ' + ','.join(str(v) for v in offsets[i:i+16]) + ',\n')
        f.write('};\n\n')

        f.write(f'const BitmapFont {font_var} = {{\n')
        f.write(f'    {data_nm}_DATA,\n')
        f.write(f'    {max_w},   // charW (max advance / monospace cell)\n')
        f.write(f'    {cell_h},   // charH\n')
        f.write(f'    0x{ASCII_FIRST:02X}, // firstChar\n')
        f.write(f'    {num},  // numChars\n')
        f.write(f'    {spacing},  // spacing\n')
        f.write(f'    {data_nm}_W,   // per-glyph advance widths\n')
        f.write(f'    {data_nm}_OFF, // per-glyph byte offsets\n')
        f.write(f'    {bytes_per_col},  // bytesPerCol\n')
        f.write('};\n\n} // namespace nema::display\n')

    total = len(data_bytes) + num + num * 2
    print(f'  {os.path.basename(out_path)}: {cell_h}px cell, {num} glyphs, '
          f'{len(data_bytes)}B bitmap + tables = {total}B total')


def emit_bmf(out_path, metrics, widths, offsets, data_bytes):
    """Write binary .bmf output.

    Header (12 bytes):
      [0]     magic       = 0xBF
      [1]     version     = 1
      [2]     charW       (max advance)
      [3]     charH       (cell height)
      [4]     firstChar
      [5]     numChars
      [6]     spacing
      [7]     bytesPerCol
      [8]     hasWidths   (1 if widths[], else 0)
      [9]     hasOffsets  (1 if offsets[], else 0)
      [10-11] dataSize    uint16_t little-endian
    Then: widths[]  (numChars bytes, if hasWidths)
    Then: offsets[] (numChars uint16_t LE, if hasOffsets)
    Then: data_bytes
    """
    cell_h        = metrics['cell_h']
    bytes_per_col = metrics['bytes_per_col']
    num           = metrics['num']
    max_w         = metrics['max_w']
    spacing       = metrics['spacing']

    # Use same base path but force .bmf extension
    bmf_path = os.path.splitext(out_path)[0] + '.bmf'

    data_size = len(data_bytes)
    has_widths  = 1
    has_offsets = 1

    header = struct.pack(
        '<BBBBBBBBBBH',
        0xBF,           # magic
        1,              # version
        max_w,          # charW
        cell_h,         # charH
        ASCII_FIRST,    # firstChar
        num,            # numChars
        spacing,        # spacing
        bytes_per_col,  # bytesPerCol
        has_widths,     # hasWidths
        has_offsets,    # hasOffsets
        data_size,      # dataSize (uint16_t LE)
    )

    with open(bmf_path, 'wb') as f:
        f.write(header)
        f.write(bytes(widths))
        # offsets: list of uint16_t → pack as LE
        f.write(struct.pack(f'<{num}H', *offsets))
        f.write(bytes(data_bytes))

    total = 12 + num + num * 2 + data_size
    print(f'  {os.path.basename(bmf_path)}: {cell_h}px cell, {num} glyphs, '
          f'{data_size}B bitmap + tables = {total}B total')


def convert(ttf_path, px_size, out_path, font_var, data_prefix, spacing=1, flags=None):
    if flags is None:
        flags = set()

    metrics, widths, offsets, data_bytes = collect_font_data(ttf_path, px_size, spacing)

    emit_c   = '--prop' in flags or '--bmf' not in flags
    emit_bin = '--bmf' in flags

    if emit_c:
        emit_proportional(out_path, font_var, data_prefix, metrics, widths, offsets, data_bytes)
    if emit_bin:
        emit_bmf(out_path, metrics, widths, offsets, data_bytes)


if __name__ == '__main__':
    args = sys.argv[1:]
    # Separate flags (--prop, --bmf) from positional args
    flags    = {a for a in args if a.startswith('--')}
    pos_args = [a for a in args if not a.startswith('--')]

    if len(pos_args) < 5:
        print('Usage: ttf_encode.py <in.ttf> <px_size> <out.cpp> <FontVar> <data_prefix> [spacing] [--prop] [--bmf]')
        sys.exit(1)
    ttf_path, px_size, out_path, font_var, data_prefix = pos_args[:5]
    spacing = int(pos_args[5]) if len(pos_args) >= 6 else 1
    convert(ttf_path, int(px_size), out_path, font_var, data_prefix, spacing, flags)
