// Plan 82 Phase 5 — Dolphin animation catalog (paths to .panim files).
// .panim files are provisioned in VFS under "anims/" by the platform at boot.
// Generated by: bun run src/index.ts batch --config asset_gen.config.json
// (Replaces dolphin_showcase.cpp — the 895 KB C-array file is no longer compiled.)
#include "nema/ui/dolphin_anim.h"

namespace nema::anim {

const DolphinEntry DOLPHIN_ENTRIES[] = {
    { "Boxing", "anims/boxing.panim", 128, 64, 2 },
};

const size_t DOLPHIN_ENTRIES_COUNT = sizeof(DOLPHIN_ENTRIES) / sizeof(DOLPHIN_ENTRIES[0]);

} // namespace nema::anim
