#!/usr/bin/env bun
// Bundle the nema SDK runtime (components + hooks + renderToTree + jsx) into one
// ESM string and embed it as a C header. The device JS engine registers this as
// the "nema" and "nema/jsx-runtime" modules so loaded .kapp apps resolve their
// imports against the SAME runtime instance the host drives. (Plan 37 Fase 2.)
import { resolve } from "path";

const out = await Bun.build({
  entrypoints: [resolve(import.meta.dir, "../src/index.ts")],
  format: "esm",
  minify: true,
  target: "browser",
});
if (!out.success) { for (const l of out.logs) console.error(l); process.exit(1); }
const js = await out.outputs[0].text();

if (js.includes(")KJS\"")) {
  console.error("runtime JS contains the raw-string delimiter; pick another"); process.exit(1);
}

const header =
`// AUTO-GENERATED by packages/nema-app-sdk/scripts/gen-runtime-header.ts — do not edit.
// The nema SDK runtime (jsx/components/hooks/renderToTree) embedded for the
// device JS engine (Plan 37). Regenerate: cd packages/nema-app-sdk && bun run gen.
#pragma once
namespace nema::js {
inline const char* const NEMA_RUNTIME_JS = R"KJS(
${js}
)KJS";
}
`;
const dest = resolve(import.meta.dir, "../../../firmware/core/include/nema/js/nema_runtime_js.h");
await Bun.write(dest, header);
console.log(`✓ embedded nema runtime → ${dest} (${js.length}B JS)`);
