// @generated from api/build/nema-api.json — DO NOT EDIT
// Generated by packages/idl/src/gen.ts (Plan 77)

// PLP wire protocol constants — generated from api/plp.pidl.
// Channel numbers, opcodes, and frame flags for the Palanu Link Protocol.
// These mirror firmware plp_codec.h and codec.ts byte-for-byte.

/** PLP channel numbers — the wire multiplexer lanes. Each frame carries a channel byte that routes it to the correct handler on both sides. Mirrors firmware: nema::plp::Channel (plp_codec.h) and codec.ts. */
export const channels = {
	control: 0,
	screen: 1,
	input: 2,
	log: 3,
	system: 4,
	ota: 5,
	ext: 6,
	event: 7,
	cli: 8,
	file: 9,
} as const;

/** Control channel opcodes (Channel 0x00). */
export const controlops = {
	hello: 1,
	ack: 2,
	reject: 3,
	auth_challenge: 32,
	auth_response: 33,
	auth_ok: 34,
	auth_fail: 35,
	auth_required: 36,
} as const;

/** File channel opcodes (Channel 0x09). */
export const fileops = {
	list: 1,
	read: 3,
	write: 4,
	mkdir: 5,
	remove: 6,
	rename: 7,
	copy: 8,
} as const;

/** Ext channel opcodes (Channel 0x06). */
export const extops = {
	inject_event: 1,
	wifi_set_networks: 2,
	app_install: 3,
	app_scan: 4,
} as const;

/** OTA channel opcodes (Channel 0x05). */
export const otaops = {
	begin: 1,
	data: 2,
	end: 3,
} as const;

/** System channel opcodes (Channel 0x04). */
export const systemops = {
	get_info: 1,
} as const;

export const Flags = {
	None: 0,
	FragMore: 1 << 0,
	Compressed: 1 << 1
} as const;
