// @generated from api/build/nema-api.json — DO NOT EDIT
// Generated by packages/idl/src/gen.ts (Plan 49)

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <string_view>
#include <tuple>
#include <vector>

// Generic result type for IDL result<T,E>.
template <typename T, typename E>
struct NemaResult {
    bool ok = false;
    T value{};
    E error{};
};

template <typename E>
struct NemaResult<void, E> {
    bool ok = false;
    E error{};
};


// Records from nema:net
// HTTP response returned by get/post.
struct HttpResponse {
    uint16_t status;
    std::string body;
};

// A Wi-Fi access point found during a scan.
struct WifiAp {
    std::string ssid;
    int32_t rssi;
    std::string auth;
};

// Records from nema:sys
// A key-value field in an event payload.
struct Field {
    std::string key;
    std::string value;
};

// Error returned when lease acquisition fails.
struct LeaseError {
    std::string code;
    std::string owner;
};

// Records from nema:wifi
// One AP found during a WiFi scan.
struct ScanResult {
    std::string bssid;
    std::string ssid;
    uint8_t channel;
    int32_t rssi;
    std::string auth;
};

// ── HostApi — generated abstract class (Plan 49) ──────────────
// Implement this ONCE in nema_host_impl.cpp (hand-written, calls rt.*).
// Adding a function to the IDL without updating the impl → build error.
struct HostApi {
    virtual ~HostApi() = default;

    // ── Plan 87 gating stubs (overridden by PermissionService/ResourceBroker) ─
    // Default: allow all — replaced in Fase 1 (perm) and Fase 2 (lease).
    virtual bool perm_check(std::string_view /*app_id*/, std::string_view /*cap*/) { return true; }
    virtual bool lease_check(std::string_view /*app_id*/, std::string_view /*cap*/) { return true; }

    // ── aether:ui ───────────────────────────────────────
    // ui/view.view-begin
    // Begin a container view (row or column flex direction). direction: "row" or "col"
    virtual int32_t view_view_begin(std::string_view direction) = 0;
    // ui/view.view-end
    // End the current container. Children added after this go to the parent.
    virtual void view_view_end() = 0;
    // ui/text.label
    // Simple text label (body style).
    virtual int32_t text_label(std::string_view content) = 0;
    // ui/text.styled
    // Styled text. variant ∈ {"title", "subtitle", "body", "caption"}.
    virtual int32_t text_styled(std::string_view content, std::string_view variant) = 0;
    // ui/interactive.button
    // Pressable button with label and on-press callback handle.
    virtual int32_t interactive_button(std::string_view label, int32_t on_press) = 0;
    // ui/scroll.scroll-begin
    // Begin a vertical scroll region. Returns handle for content children.
    virtual int32_t scroll_scroll_begin() = 0;
    // ui/scroll.scroll-end
    // End the scroll region.
    virtual void scroll_scroll_end() = 0;

    // ── nema:bt ───────────────────────────────────────
    // bt/ble.enable [@blocking]
    // Whether the BLE controller is enabled.
    virtual NemaResult<void, std::string> ble_enable() = 0;
    // bt/ble.disable
    // Stop the BLE controller.
    virtual void ble_disable() = 0;
    // bt/ble.is-enabled
    // Whether BLE is active and advertising/connected.
    virtual bool ble_is_enabled() = 0;

    // ── nema:input ───────────────────────────────────────
    // input/input.hint
    // Get the hardware-specific hint label for an Action.
    virtual std::string input_hint(std::string_view action) = 0;
    // input/input.actions
    // List all supported actions on this device.
    virtual std::vector<std::string> input_actions() = 0;

    // ── nema:media ───────────────────────────────────────
    // media/audio-input.list
    // List available audio input devices.
    virtual std::vector<std::string> audio_input_list() = 0;
    // media/audio-output.list
    // List available audio output devices.
    virtual std::vector<std::string> audio_output_list() = 0;
    // media/camera.list
    // List available camera devices.
    virtual std::vector<std::string> camera_list() = 0;
    // media/camera.capture [@blocking]
    // Capture a frame from the default camera. @blocking — runs on worker.
    virtual NemaResult<std::string, std::string> camera_capture() = 0;

    // ── nema:net ───────────────────────────────────────
    // net/http.get [@blocking]
    // HTTPS GET. Returns the response or an error string on transport failure.
    virtual NemaResult<HttpResponse, std::string> http_get(std::string_view url) = 0;
    // net/http.post [@blocking]
    // HTTPS POST with a body and Content-Type header.
    virtual NemaResult<HttpResponse, std::string> http_post(std::string_view url, std::string_view body, std::string_view content_type) = 0;
    // net/wifi.is-connected
    // Whether the device is currently connected to an AP.
    virtual bool wifi_is_connected() = 0;
    // net/wifi.ssid
    // The SSID of the currently connected AP, or empty string.
    virtual std::string wifi_ssid() = 0;
    // net/wifi.ip
    // The local IP address, or empty string.
    virtual std::string wifi_ip() = 0;
    // net/wifi.scan [@blocking]
    // Start a Wi-Fi scan. @blocking — runs on worker.
    virtual std::vector<WifiAp> wifi_scan() = 0;
    // net/wifi.connect [@blocking]
    // Connect to an AP.
    virtual NemaResult<void, std::string> wifi_connect(std::string_view ssid, std::string_view password) = 0;
    // net/wifi.disconnect
    // Disconnect from the current AP.
    virtual void wifi_disconnect() = 0;

    // ── nema:profile ───────────────────────────────────────
    // profile/profile.user-name
    // The device owner's display name (e.g. "Alice").
    virtual std::string profile_user_name() = 0;
    // profile/profile.device-name
    // The user-assigned device name (e.g. "My Palanu").
    virtual std::string profile_device_name() = 0;
    // profile/profile.has-password
    // Whether a password/PIN has been set.
    virtual bool profile_has_password() = 0;
    // profile/profile.verify-password
    // Verify a password/PIN candidate. Uses constant-time comparison. Returns false if no password is set.
    virtual bool profile_verify_password(std::string_view input) = 0;

    // ── nema:storage ───────────────────────────────────────
    // storage/kv.get
    // Read a string value. Absent key → none.
    virtual std::optional<std::string> kv_get(std::string_view key) = 0;
    // storage/kv.set
    // Write a string value (commits immediately).
    virtual void kv_set(std::string_view key, std::string_view value) = 0;
    // storage/kv.get-int
    // Read a 64-bit int. Absent key → none.
    virtual std::optional<int64_t> kv_get_int(std::string_view key) = 0;
    // storage/kv.set-int
    // Write a 64-bit int (commits immediately).
    virtual void kv_set_int(std::string_view key, int64_t value) = 0;
    // storage/kv.remove
    // Delete a key. Returns true if the key existed.
    virtual bool kv_remove(std::string_view key) = 0;
    // storage/fs.read-file
    // Read a file as a UTF-8 string. Returns none if the file does not exist.
    virtual std::optional<std::string> fs_read_file(std::string_view name) = 0;
    // storage/fs.write-file
    // Write (create or overwrite) a file with UTF-8 content.
    virtual bool fs_write_file(std::string_view name, std::string_view data) = 0;
    // storage/fs.list-files
    // List files in the app's storage directory.
    virtual std::vector<std::string> fs_list_files() = 0;
    // storage/fs.remove-file
    // Delete a file. Returns true if it existed.
    virtual bool fs_remove_file(std::string_view name) = 0;
    // storage/fs.bytes-used
    // Total bytes used across all files for this app (internal + SD).
    virtual uint64_t fs_bytes_used() = 0;

    // ── nema:sys ───────────────────────────────────────
    // sys/log.log
    // Log a message at the given level. level ∈ {"trace", "debug", "info", "warn", "error", "fatal"}
    virtual void log_log(std::string_view level, std::string_view tag, std::string_view msg) = 0;
    // sys/device.name
    // Board/product name, e.g. "dev-board", "skyrizz-e32".
    virtual std::string device_name() = 0;
    // sys/device.caps
    // All static capabilities this box was built with (Plan 42).
    virtual std::vector<std::string> device_caps() = 0;
    // sys/device.has
    // Static: was this box built able to do X?
    virtual bool device_has(std::string_view cap) = 0;
    // sys/device.available
    // Dynamic: is X up and usable right now? (Plan 42 liveness)
    virtual bool device_available(std::string_view cap) = 0;
    // sys/events.subscribe
    // Subscribe to an event name (or "*" for all).
    virtual int32_t events_subscribe(std::string_view name, int32_t handler) = 0;
    // sys/events.unsubscribe
    // Remove a subscription by handle returned from subscribe.
    virtual void events_unsubscribe(int32_t token) = 0;
    // sys/events.publish
    // Publish an event with optional string fields.
    virtual void events_publish(std::string_view name, const std::vector<Field>& fields) = 0;
    // sys/perm.status
    // Query permission status for a capability. Returns: 0=not_asked  1=granted  2=denied
    virtual uint8_t perm_status(std::string_view cap) = 0;
    // sys/perm.request
    // Request permission for a capability. For sensitive capabilities this triggers the Allow/Deny screen. Returns: 1=granted  2=denied
    virtual uint8_t perm_request(std::string_view cap) = 0;
    // sys/lease.acquire
    // Acquire an exclusive lease for a capability. Returns a lease handle on success, or a lease-error if busy/denied.
    virtual NemaResult<uint32_t, LeaseError> lease_acquire(std::string_view cap) = 0;
    // sys/lease.release
    // Release a previously acquired lease.
    virtual NemaResult<void, std::string> lease_release(uint32_t lease_handle) = 0;
    // sys/tasks.submit
    // Submit a job to run on a worker thread; done() is called on the UI loop. @blocking marks that the job may block (http, wifi scan, ble enable).
    virtual void tasks_submit(int32_t job, int32_t done) = 0;
    // sys/tasks.timeout
    // Schedule a callback after delay milliseconds (one-shot).
    virtual int32_t tasks_timeout(uint32_t ms, int32_t callback) = 0;
    // sys/tasks.interval
    // Schedule a repeating callback every interval milliseconds.
    virtual int32_t tasks_interval(uint32_t ms, int32_t callback) = 0;
    // sys/tasks.cancel
    // Cancel a pending timeout/interval by handle.
    virtual void tasks_cancel(int32_t token) = 0;

    // ── nema:wifi ───────────────────────────────────────
    // wifi/radio.scan [@blocking]
    // Scan for visible APs. @blocking — runs on worker. Auto-grant (benign): no permission prompt. No exclusive lease required.
    virtual NemaResult<std::vector<ScanResult>, std::string> radio_scan() = 0;
    // wifi/radio.monitor-open
    // Open promiscuous/monitor mode on the given channel. Requires user permission (sensitive) and an exclusive lease.
    virtual NemaResult<void, std::string> radio_monitor_open(uint8_t channel) = 0;
    // wifi/radio.monitor-read [@blocking]
    // Read raw 802.11 frames from the ring buffer (up to max bytes). Drops frames when ring is full — radio never stalls.
    virtual NemaResult<std::vector<uint8_t>, std::string> radio_monitor_read(uint32_t max) = 0;
    // wifi/radio.monitor-close
    // Close monitor mode and release promiscuous capture.
    virtual NemaResult<void, std::string> radio_monitor_close() = 0;
    // wifi/radio.inject
    // Inject a raw 802.11 frame on the given channel.
    virtual NemaResult<void, std::string> radio_inject(uint8_t channel, const std::vector<uint8_t>& frame) = 0;

};
