// @generated from api/build/nema-api.json — DO NOT EDIT
// Generated by packages/idl/src/gen.ts (Plan 49)

#include "nema/js/js_engine.h"
#include "host/nema_api.gen.h"
#include "nema/system/capabilities.h"
#include "nema/system/capability_registry.h"
#include <string>
#include <vector>

using nema::js::JsEngine;

namespace {

// QuickJS ↔ C++ marshalling helpers (generated once, shared by all wrappers).
// These are deliberately simple wrappers; the generator emits calls to them
// rather than inlining the marshalling for every function.

static JsEngine* engineOf(JSContext* ctx) {
    return static_cast<JsEngine*>(JS_GetContextOpaque(ctx));
}

static std::string jsToString(JSContext* ctx, JSValueConst v) {
    std::string r;
    const char* s = JS_ToCString(ctx, v);
    if (s) { r = s; JS_FreeCString(ctx, s); }
    return r;
}

static int32_t jsToI32(JSContext* ctx, JSValueConst v) {
    int32_t r = 0;
    JS_ToInt32(ctx, &r, v);
    return r;
}

static uint32_t jsToU32(JSContext* ctx, JSValueConst v) {
    uint32_t r = 0;
    JS_ToUint32(ctx, &r, v);
    return r;
}

static int64_t jsToI64(JSContext* ctx, JSValueConst v) {
    int64_t r = 0;
    JS_ToInt64(ctx, &r, v);
    return r;
}

static uint64_t jsToU64(JSContext* ctx, JSValueConst v) {
    int64_t r = 0;
    JS_ToInt64(ctx, &r, v);
    return static_cast<uint64_t>(r);
}

static double jsToDouble(JSContext* ctx, JSValueConst v) {
    double r = 0;
    JS_ToFloat64(ctx, &r, v);
    return r;
}

// Read raw bytes from a JS ArrayBuffer or TypedArray (Uint8Array, Int16Array, …)
// into a byte vector. Used for binary IDL params (list<u8>), e.g. PCM audio. The
// underlying bytes are copied so the vector outlives the JS value. Returns empty
// if v is neither an ArrayBuffer nor a TypedArray.
static std::vector<uint8_t> jsToBytes(JSContext* ctx, JSValueConst v) {
    std::vector<uint8_t> out;
    // TypedArray → underlying ArrayBuffer + byte window.
    size_t byteOffset = 0, byteLen = 0, bytesPerEl = 0;
    JSValue ab = JS_GetTypedArrayBuffer(ctx, v, &byteOffset, &byteLen, &bytesPerEl);
    if (!JS_IsException(ab)) {
        size_t abLen = 0;
        uint8_t* p = JS_GetArrayBuffer(ctx, &abLen, ab);
        if (p && byteOffset + byteLen <= abLen)
            out.assign(p + byteOffset, p + byteOffset + byteLen);
        JS_FreeValue(ctx, ab);
        return out;
    }
    JS_FreeValue(ctx, JS_GetException(ctx)); // clear the "not a TypedArray" exception
    // Plain ArrayBuffer.
    size_t abLen = 0;
    uint8_t* p = JS_GetArrayBuffer(ctx, &abLen, v);
    if (p) out.assign(p, p + abLen);
    return out;
}

static void setFn(JSContext* ctx, JSValue obj, const char* name, JSCFunction* fn, int argc) {
    JS_SetPropertyStr(ctx, obj, name, JS_NewCFunction(ctx, fn, name, argc));
}

// Marshal std::optional<T> → JS (null or wrapped value)
template <typename T, typename F>
static JSValue marshalOption(JSContext* ctx, const std::optional<T>& opt, F wrap) {
    if (!opt.has_value()) return JS_NULL;
    return wrap(ctx, opt.value());
}

// Marshal std::vector<T> → JS Array
template <typename T, typename F>
static JSValue marshalList(JSContext* ctx, const std::vector<T>& vec, F wrap) {
    JSValue arr = JS_NewArray(ctx);
    for (uint32_t i = 0; i < vec.size(); i++)
        JS_SetPropertyUint32(ctx, arr, i, wrap(ctx, vec[i]));
    return arr;
}

// Marshal NemaResult<T,E> → JS (ok value, or throw with wrapErr result as message).
// wrapErr can produce JS_NewString for string errors or marshalRecord for struct errors.
template <typename T, typename E, typename FW, typename FE>
static JSValue marshalResult(JSContext* ctx, const NemaResult<T,E>& r, FW wrapOk, FE wrapErr) {
    if (r.ok) return wrapOk(ctx, r.value);
    return wrapErr(ctx, r.error);
}

template <typename E, typename FE>
static JSValue marshalResultVoid(JSContext* ctx, const NemaResult<void,E>& r, FE wrapErr) {
    if (r.ok) return JS_NewObject(ctx);
    return wrapErr(ctx, r.error);
}

// Stub marshalling for records + tuples (used by @future interfaces).
// Full marshalling will be generated in a later phase.
template <typename T>
static JSValue marshalRecord(JSContext* ctx, const T&) {
    (void)ctx;
    return JS_UNDEFINED;
}
template <typename... Ts>
static JSValue marshalTuple(JSContext* ctx, const std::tuple<Ts...>&) {
    (void)ctx;
    return JS_UNDEFINED;
}


// ── Generated function wrappers ───────────────────────────

// view.view-begin
static JSValue nema_view_view_begin(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string direction = jsToString(ctx, argv[0]);
    auto __ret = host->view_view_begin(direction);
    return JS_NewInt32(ctx, __ret);
}

// view.view-end
static JSValue nema_view_view_end(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    host->view_view_end();
    return JS_UNDEFINED;
}

// text.label
static JSValue nema_text_label(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string content = jsToString(ctx, argv[0]);
    auto __ret = host->text_label(content);
    return JS_NewInt32(ctx, __ret);
}

// text.styled
static JSValue nema_text_styled(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string content = jsToString(ctx, argv[0]);
    std::string variant = jsToString(ctx, argv[1]);
    auto __ret = host->text_styled(content, variant);
    return JS_NewInt32(ctx, __ret);
}

// interactive.button
static JSValue nema_interactive_button(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string label = jsToString(ctx, argv[0]);
    auto on_press = jsToI32(ctx, argv[1]);
    auto __ret = host->interactive_button(label, on_press);
    return JS_NewInt32(ctx, __ret);
}

// scroll.scroll-begin
static JSValue nema_scroll_scroll_begin(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->scroll_scroll_begin();
    return JS_NewInt32(ctx, __ret);
}

// scroll.scroll-end
static JSValue nema_scroll_scroll_end(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    host->scroll_scroll_end();
    return JS_UNDEFINED;
}

// ble.enable
// @blocking — dispatched via TaskRunner (the host wraps as async).
static JSValue nema_ble_enable(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->ble_enable();
    return marshalResultVoid(ctx, __ret, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// ble.disable
static JSValue nema_ble_disable(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    host->ble_disable();
    return JS_UNDEFINED;
}

// ble.is-enabled
static JSValue nema_ble_is_enabled(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->ble_is_enabled();
    return JS_NewBool(ctx, __ret);
}

// input.hint
static JSValue nema_input_hint(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string action = jsToString(ctx, argv[0]);
    auto __ret = host->input_hint(action);
    return JS_NewString(ctx, __ret.c_str());
}

// input.actions
static JSValue nema_input_actions(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->input_actions();
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// led.list
static JSValue nema_led_list(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->led_list();
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// led.solid
static JSValue nema_led_solid(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto index = jsToI32(ctx, argv[0]);
    auto r = jsToU32(ctx, argv[1]);
    auto g = jsToU32(ctx, argv[2]);
    auto b = jsToU32(ctx, argv[3]);
    host->led_solid(index, r, g, b);
    return JS_UNDEFINED;
}

// led.blink
static JSValue nema_led_blink(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto index = jsToI32(ctx, argv[0]);
    auto r = jsToU32(ctx, argv[1]);
    auto g = jsToU32(ctx, argv[2]);
    auto b = jsToU32(ctx, argv[3]);
    auto on_ms = jsToU32(ctx, argv[4]);
    auto off_ms = jsToU32(ctx, argv[5]);
    auto cycles = jsToI32(ctx, argv[6]);
    host->led_blink(index, r, g, b, on_ms, off_ms, cycles);
    return JS_UNDEFINED;
}

// led.off
static JSValue nema_led_off(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto index = jsToI32(ctx, argv[0]);
    host->led_off(index);
    return JS_UNDEFINED;
}

// led.notify
static JSValue nema_led_notify(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto intent = jsToU32(ctx, argv[0]);
    host->led_notify(intent);
    return JS_UNDEFINED;
}

// led.brightness
static JSValue nema_led_brightness(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto index = jsToI32(ctx, argv[0]);
    auto level = jsToU32(ctx, argv[1]);
    host->led_brightness(index, level);
    return JS_UNDEFINED;
}

// audio-input.list
static JSValue nema_audio_input_list(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->audio_input_list();
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// audio-output.list
static JSValue nema_audio_output_list(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->audio_output_list();
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// audio-output.set-volume
static JSValue nema_audio_output_set_volume(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto level = jsToU32(ctx, argv[0]);
    host->audio_output_set_volume(level);
    return JS_UNDEFINED;
}

// audio-output.play-tone
static JSValue nema_audio_output_play_tone(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto freq = jsToU32(ctx, argv[0]);
    auto ms = jsToU32(ctx, argv[1]);
    host->audio_output_play_tone(freq, ms);
    return JS_UNDEFINED;
}

// audio-output.play-pcm
static JSValue nema_audio_output_play_pcm(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::vector<uint8_t> data = jsToBytes(ctx, argv[0]);
    auto sample_rate = jsToU32(ctx, argv[1]);
    host->audio_output_play_pcm(data, sample_rate);
    return JS_UNDEFINED;
}

// camera.list
static JSValue nema_camera_list(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->camera_list();
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// camera.capture
// @blocking — dispatched via TaskRunner (the host wraps as async).
static JSValue nema_camera_capture(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->camera_capture();
    return marshalResult(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); }, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// http.get
// @blocking — dispatched via TaskRunner (the host wraps as async).
static JSValue nema_http_get(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string url = jsToString(ctx, argv[0]);
    auto __ret = host->http_get(url);
    return marshalResult(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return marshalRecord(ctx, v); }, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// http.post
// @blocking — dispatched via TaskRunner (the host wraps as async).
static JSValue nema_http_post(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string url = jsToString(ctx, argv[0]);
    std::string body = jsToString(ctx, argv[1]);
    std::string content_type = jsToString(ctx, argv[2]);
    auto __ret = host->http_post(url, body, content_type);
    return marshalResult(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return marshalRecord(ctx, v); }, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// http.request
// @blocking — dispatched via TaskRunner (the host wraps as async).
static JSValue nema_http_request(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string method = jsToString(ctx, argv[0]);
    std::string url = jsToString(ctx, argv[1]);
    std::string headers = jsToString(ctx, argv[2]);
    std::string body = jsToString(ctx, argv[3]);
    auto __ret = host->http_request(method, url, headers, body);
    return marshalResult(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return marshalRecord(ctx, v); }, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// wifi.is-connected
static JSValue nema_wifi_is_connected(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->wifi_is_connected();
    return JS_NewBool(ctx, __ret);
}

// wifi.ssid
static JSValue nema_wifi_ssid(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->wifi_ssid();
    return JS_NewString(ctx, __ret.c_str());
}

// wifi.ip
static JSValue nema_wifi_ip(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->wifi_ip();
    return JS_NewString(ctx, __ret.c_str());
}

// wifi.scan
// @blocking — dispatched via TaskRunner (the host wraps as async).
static JSValue nema_wifi_scan(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->wifi_scan();
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return marshalRecord(ctx, v); });
}

// wifi.connect
// @blocking — dispatched via TaskRunner (the host wraps as async).
static JSValue nema_wifi_connect(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string ssid = jsToString(ctx, argv[0]);
    std::string password = jsToString(ctx, argv[1]);
    auto __ret = host->wifi_connect(ssid, password);
    return marshalResultVoid(ctx, __ret, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// wifi.disconnect
static JSValue nema_wifi_disconnect(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    host->wifi_disconnect();
    return JS_UNDEFINED;
}

// profile.user-name
static JSValue nema_profile_user_name(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->profile_user_name();
    return JS_NewString(ctx, __ret.c_str());
}

// profile.device-name
static JSValue nema_profile_device_name(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->profile_device_name();
    return JS_NewString(ctx, __ret.c_str());
}

// profile.has-password
static JSValue nema_profile_has_password(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->profile_has_password();
    return JS_NewBool(ctx, __ret);
}

// profile.verify-password
static JSValue nema_profile_verify_password(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string input = jsToString(ctx, argv[0]);
    auto __ret = host->profile_verify_password(input);
    return JS_NewBool(ctx, __ret);
}

// sensors.list
static JSValue nema_sensors_list(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->sensors_list();
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// sensors.read
static JSValue nema_sensors_read(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto index = jsToU32(ctx, argv[0]);
    auto __ret = host->sensors_read(index);
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// kv.get
static JSValue nema_kv_get(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string key = jsToString(ctx, argv[0]);
    auto __ret = host->kv_get(key);
    return marshalOption(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// kv.set
static JSValue nema_kv_set(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string key = jsToString(ctx, argv[0]);
    std::string value = jsToString(ctx, argv[1]);
    host->kv_set(key, value);
    return JS_UNDEFINED;
}

// kv.get-int
static JSValue nema_kv_get_int(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string key = jsToString(ctx, argv[0]);
    auto __ret = host->kv_get_int(key);
    return marshalOption(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewInt64(ctx, v); });
}

// kv.set-int
static JSValue nema_kv_set_int(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string key = jsToString(ctx, argv[0]);
    auto value = jsToI64(ctx, argv[1]);
    host->kv_set_int(key, value);
    return JS_UNDEFINED;
}

// kv.remove
static JSValue nema_kv_remove(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string key = jsToString(ctx, argv[0]);
    auto __ret = host->kv_remove(key);
    return JS_NewBool(ctx, __ret);
}

// fs.read-file
static JSValue nema_fs_read_file(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string name = jsToString(ctx, argv[0]);
    auto __ret = host->fs_read_file(name);
    return marshalOption(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// fs.write-file
static JSValue nema_fs_write_file(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string name = jsToString(ctx, argv[0]);
    std::string data = jsToString(ctx, argv[1]);
    auto __ret = host->fs_write_file(name, data);
    return JS_NewBool(ctx, __ret);
}

// fs.list-files
static JSValue nema_fs_list_files(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->fs_list_files();
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// fs.remove-file
static JSValue nema_fs_remove_file(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string name = jsToString(ctx, argv[0]);
    auto __ret = host->fs_remove_file(name);
    return JS_NewBool(ctx, __ret);
}

// fs.bytes-used
static JSValue nema_fs_bytes_used(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->fs_bytes_used();
    return JS_NewInt64(ctx, __ret);
}

// log.log
static JSValue nema_log_log(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string level = jsToString(ctx, argv[0]);
    std::string tag = jsToString(ctx, argv[1]);
    std::string msg = jsToString(ctx, argv[2]);
    host->log_log(level, tag, msg);
    return JS_UNDEFINED;
}

// device.name
static JSValue nema_device_name(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->device_name();
    return JS_NewString(ctx, __ret.c_str());
}

// device.caps
static JSValue nema_device_caps(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->device_caps();
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// device.has
static JSValue nema_device_has(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string cap = jsToString(ctx, argv[0]);
    auto __ret = host->device_has(cap);
    return JS_NewBool(ctx, __ret);
}

// device.available
static JSValue nema_device_available(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string cap = jsToString(ctx, argv[0]);
    auto __ret = host->device_available(cap);
    return JS_NewBool(ctx, __ret);
}

// events.subscribe
static JSValue nema_events_subscribe(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string name = jsToString(ctx, argv[0]);
    auto handler = jsToI32(ctx, argv[1]);
    auto __ret = host->events_subscribe(name, handler);
    return JS_NewInt32(ctx, __ret);
}

// events.unsubscribe
static JSValue nema_events_unsubscribe(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto token = jsToI32(ctx, argv[0]);
    host->events_unsubscribe(token);
    return JS_UNDEFINED;
}

// events.publish
static JSValue nema_events_publish(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string name = jsToString(ctx, argv[0]);
    std::vector<Field> fields = {};
    host->events_publish(name, fields);
    return JS_UNDEFINED;
}

// perm.status
static JSValue nema_perm_status(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string cap = jsToString(ctx, argv[0]);
    auto __ret = host->perm_status(cap);
    return JS_NewInt32(ctx, __ret);
}

// perm.request
static JSValue nema_perm_request(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string cap = jsToString(ctx, argv[0]);
    auto __ret = host->perm_request(cap);
    return JS_NewInt32(ctx, __ret);
}

// lease.acquire
static JSValue nema_lease_acquire(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    std::string cap = jsToString(ctx, argv[0]);
    auto __ret = host->lease_acquire(cap);
    return marshalResult(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewInt32(ctx, v); }, [ctx](JSContext* c, auto& e) { return marshalRecord(ctx, e); });
}

// lease.release
static JSValue nema_lease_release(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto lease_handle = jsToU32(ctx, argv[0]);
    auto __ret = host->lease_release(lease_handle);
    return marshalResultVoid(ctx, __ret, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// tasks.submit
static JSValue nema_tasks_submit(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto job = jsToI32(ctx, argv[0]);
    auto done = jsToI32(ctx, argv[1]);
    host->tasks_submit(job, done);
    return JS_UNDEFINED;
}

// tasks.timeout
static JSValue nema_tasks_timeout(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto ms = jsToU32(ctx, argv[0]);
    auto callback = jsToI32(ctx, argv[1]);
    auto __ret = host->tasks_timeout(ms, callback);
    return JS_NewInt32(ctx, __ret);
}

// tasks.interval
static JSValue nema_tasks_interval(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto ms = jsToU32(ctx, argv[0]);
    auto callback = jsToI32(ctx, argv[1]);
    auto __ret = host->tasks_interval(ms, callback);
    return JS_NewInt32(ctx, __ret);
}

// tasks.cancel
static JSValue nema_tasks_cancel(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto token = jsToI32(ctx, argv[0]);
    host->tasks_cancel(token);
    return JS_UNDEFINED;
}

// wallet.networks
static JSValue nema_wallet_networks(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->wallet_networks();
    return marshalList(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); });
}

// wallet.ready
static JSValue nema_wallet_ready(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->wallet_ready();
    return JS_NewBool(ctx, __ret);
}

// wallet.address
static JSValue nema_wallet_address(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    // @capability("wallet.read") @tier(sensitive)
    if (!host->perm_check(e->appId(), "wallet.read"))
        return JS_ThrowTypeError(ctx, "ERR_PERMISSION: wallet.read");

    std::string network_id = jsToString(ctx, argv[0]);
    auto index = jsToU32(ctx, argv[1]);
    auto __ret = host->wallet_address(network_id, index);
    return marshalResult(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); }, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// wallet.sign-message
static JSValue nema_wallet_sign_message(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    // @capability("wallet.sign") @tier(sensitive)
    if (!host->perm_check(e->appId(), "wallet.sign"))
        return JS_ThrowTypeError(ctx, "ERR_PERMISSION: wallet.sign");

    std::string network_id = jsToString(ctx, argv[0]);
    auto index = jsToU32(ctx, argv[1]);
    std::string message = jsToString(ctx, argv[2]);
    auto __ret = host->wallet_sign_message(network_id, index, message);
    return marshalResult(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); }, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// wallet.sign-transaction
static JSValue nema_wallet_sign_transaction(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    // @capability("wallet.sign") @tier(sensitive)
    if (!host->perm_check(e->appId(), "wallet.sign"))
        return JS_ThrowTypeError(ctx, "ERR_PERMISSION: wallet.sign");

    std::string network_id = jsToString(ctx, argv[0]);
    auto index = jsToU32(ctx, argv[1]);
    std::string raw_tx_hex = jsToString(ctx, argv[2]);
    auto __ret = host->wallet_sign_transaction(network_id, index, raw_tx_hex);
    return marshalResult(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewString(ctx, v.c_str()); }, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// radio.scan
// @blocking — dispatched via TaskRunner (the host wraps as async).
static JSValue nema_radio_scan(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    auto __ret = host->radio_scan();
    return marshalResult(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return marshalList(ctx, v, [ctx](JSContext* c, auto& v) { (void)c; return marshalRecord(ctx, v); }); }, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// radio.monitor-open
static JSValue nema_radio_monitor_open(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    // @capability("net.wifi.monitor") @tier(sensitive) @lease
    if (!host->perm_check(e->appId(), "net.wifi.monitor"))
        return JS_ThrowTypeError(ctx, "ERR_PERMISSION: net.wifi.monitor");
    if (!host->lease_check(e->appId(), "net.wifi.monitor"))
        return JS_ThrowTypeError(ctx, "ERR_NO_LEASE: net.wifi.monitor");

    auto channel = jsToU32(ctx, argv[0]);
    auto __ret = host->radio_monitor_open(channel);
    return marshalResultVoid(ctx, __ret, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// radio.monitor-read
// @blocking — dispatched via TaskRunner (the host wraps as async).
static JSValue nema_radio_monitor_read(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    // @capability("net.wifi.monitor") @tier(sensitive) @lease
    if (!host->perm_check(e->appId(), "net.wifi.monitor"))
        return JS_ThrowTypeError(ctx, "ERR_PERMISSION: net.wifi.monitor");
    if (!host->lease_check(e->appId(), "net.wifi.monitor"))
        return JS_ThrowTypeError(ctx, "ERR_NO_LEASE: net.wifi.monitor");

    auto max = jsToU32(ctx, argv[0]);
    auto __ret = host->radio_monitor_read(max);
    return marshalResult(ctx, __ret, [ctx](JSContext* c, auto& v) { (void)c; return marshalList(ctx, v, [ctx](JSContext* c, auto& v) { (void)c; return JS_NewInt32(ctx, v); }); }, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// radio.monitor-close
static JSValue nema_radio_monitor_close(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    // @capability("net.wifi.monitor") @tier(sensitive) @lease
    if (!host->perm_check(e->appId(), "net.wifi.monitor"))
        return JS_ThrowTypeError(ctx, "ERR_PERMISSION: net.wifi.monitor");
    if (!host->lease_check(e->appId(), "net.wifi.monitor"))
        return JS_ThrowTypeError(ctx, "ERR_NO_LEASE: net.wifi.monitor");

    auto __ret = host->radio_monitor_close();
    return marshalResultVoid(ctx, __ret, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

// radio.inject
static JSValue nema_radio_inject(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    (void)argc; (void)argv;
    auto* e = engineOf(ctx);
    auto* host = e->hostApi();
    if (!host) return JS_UNDEFINED;

    // @capability("net.wifi.inject") @tier(sensitive) @lease
    if (!host->perm_check(e->appId(), "net.wifi.inject"))
        return JS_ThrowTypeError(ctx, "ERR_PERMISSION: net.wifi.inject");
    if (!host->lease_check(e->appId(), "net.wifi.inject"))
        return JS_ThrowTypeError(ctx, "ERR_NO_LEASE: net.wifi.inject");

    auto channel = jsToU32(ctx, argv[0]);
    std::vector<uint8_t> frame = jsToBytes(ctx, argv[1]);
    auto __ret = host->radio_inject(channel, frame);
    return marshalResultVoid(ctx, __ret, [ctx](JSContext* c, auto& e) { return JS_ThrowTypeError(c, "%s", e.c_str()); });
}

} // anon namespace

// ── Generated registration ────────────────────────────────

// Build the `nema` global namespace tree + register all C functions.
// Namespace structure matches the IDL (Plan 48 Fase 4 canonical paths).
void installNemaApi(JSContext* ctx, HostApi* host, nema::CapabilityRegistry& caps) {
    JSValue g = JS_GetGlobalObject(ctx);
    JSValue nema = JS_NewObject(ctx);

    JSValue bt = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, nema, "bt", bt);
    JSValue bt_ble = JS_NewObject(ctx);
    if (caps.has(nema::caps::BtBle)) {
        JS_SetPropertyStr(ctx, bt, "ble", bt_ble);
    }
    setFn(ctx, bt_ble, "enable", nema_ble_enable, 0);
    setFn(ctx, bt_ble, "disable", nema_ble_disable, 0);
    setFn(ctx, bt_ble, "isEnabled", nema_ble_is_enabled, 0);

    JSValue led = JS_NewObject(ctx);
    if (caps.has(nema::caps::Led)) {
        JS_SetPropertyStr(ctx, nema, "led", led);
    }
    setFn(ctx, led, "list", nema_led_list, 0);
    setFn(ctx, led, "solid", nema_led_solid, 4);
    setFn(ctx, led, "blink", nema_led_blink, 7);
    setFn(ctx, led, "off", nema_led_off, 1);
    setFn(ctx, led, "notify", nema_led_notify, 1);
    setFn(ctx, led, "brightness", nema_led_brightness, 2);

    JSValue media = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, nema, "media", media);
    JSValue media_audio_input = JS_NewObject(ctx);
    if (caps.has(nema::caps::AudioInput)) {
        JS_SetPropertyStr(ctx, media, "audio-input", media_audio_input);
    }
    setFn(ctx, media_audio_input, "list", nema_audio_input_list, 0);

    JSValue media_audio_output = JS_NewObject(ctx);
    if (caps.has(nema::caps::AudioOutput)) {
        JS_SetPropertyStr(ctx, media, "audio-output", media_audio_output);
    }
    setFn(ctx, media_audio_output, "list", nema_audio_output_list, 0);
    setFn(ctx, media_audio_output, "setVolume", nema_audio_output_set_volume, 1);
    setFn(ctx, media_audio_output, "playTone", nema_audio_output_play_tone, 2);
    setFn(ctx, media_audio_output, "playPcm", nema_audio_output_play_pcm, 2);

    JSValue media_camera = JS_NewObject(ctx);
    if (caps.has(nema::caps::Camera)) {
        JS_SetPropertyStr(ctx, media, "camera", media_camera);
    }
    setFn(ctx, media_camera, "list", nema_camera_list, 0);
    setFn(ctx, media_camera, "capture", nema_camera_capture, 0);

    JSValue net = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, nema, "net", net);
    JSValue net_http = JS_NewObject(ctx);
    if (caps.has(nema::caps::NetHttp)) {
        JS_SetPropertyStr(ctx, net, "http", net_http);
    }
    setFn(ctx, net_http, "get", nema_http_get, 1);
    setFn(ctx, net_http, "post", nema_http_post, 3);
    setFn(ctx, net_http, "request", nema_http_request, 4);

    JSValue net_wifi = JS_NewObject(ctx);
    if (caps.has(nema::caps::NetWifi)) {
        JS_SetPropertyStr(ctx, net, "wifi", net_wifi);
    }
    setFn(ctx, net_wifi, "isConnected", nema_wifi_is_connected, 0);
    setFn(ctx, net_wifi, "ssid", nema_wifi_ssid, 0);
    setFn(ctx, net_wifi, "ip", nema_wifi_ip, 0);
    setFn(ctx, net_wifi, "scan", nema_wifi_scan, 0);
    setFn(ctx, net_wifi, "connect", nema_wifi_connect, 2);
    setFn(ctx, net_wifi, "disconnect", nema_wifi_disconnect, 0);

    JSValue sensors = JS_NewObject(ctx);
    if (caps.has(nema::caps::Sensors)) {
        JS_SetPropertyStr(ctx, nema, "sensors", sensors);
    }
    setFn(ctx, sensors, "list", nema_sensors_list, 0);
    setFn(ctx, sensors, "read", nema_sensors_read, 1);

    JSValue storage = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, nema, "storage", storage);
    JSValue storage_kv = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, storage, "kv", storage_kv);
    setFn(ctx, storage_kv, "get", nema_kv_get, 1);
    setFn(ctx, storage_kv, "set", nema_kv_set, 2);
    setFn(ctx, storage_kv, "getInt", nema_kv_get_int, 1);
    setFn(ctx, storage_kv, "setInt", nema_kv_set_int, 2);
    setFn(ctx, storage_kv, "remove", nema_kv_remove, 1);

    JSValue storage_fs = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, storage, "fs", storage_fs);
    setFn(ctx, storage_fs, "readFile", nema_fs_read_file, 1);
    setFn(ctx, storage_fs, "writeFile", nema_fs_write_file, 2);
    setFn(ctx, storage_fs, "listFiles", nema_fs_list_files, 0);
    setFn(ctx, storage_fs, "removeFile", nema_fs_remove_file, 1);
    setFn(ctx, storage_fs, "bytesUsed", nema_fs_bytes_used, 0);

    JSValue sys = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, nema, "sys", sys);
    JSValue sys_log = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, sys, "log", sys_log);
    setFn(ctx, sys_log, "log", nema_log_log, 3);

    JSValue sys_device = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, sys, "device", sys_device);
    setFn(ctx, sys_device, "name", nema_device_name, 0);
    setFn(ctx, sys_device, "caps", nema_device_caps, 0);
    setFn(ctx, sys_device, "has", nema_device_has, 1);
    setFn(ctx, sys_device, "available", nema_device_available, 1);

    JSValue sys_events = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, sys, "events", sys_events);
    setFn(ctx, sys_events, "subscribe", nema_events_subscribe, 2);
    setFn(ctx, sys_events, "unsubscribe", nema_events_unsubscribe, 1);
    setFn(ctx, sys_events, "publish", nema_events_publish, 2);

    JSValue sys_perm = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, sys, "perm", sys_perm);
    setFn(ctx, sys_perm, "status", nema_perm_status, 1);
    setFn(ctx, sys_perm, "request", nema_perm_request, 1);

    JSValue sys_lease = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, sys, "lease", sys_lease);
    setFn(ctx, sys_lease, "acquire", nema_lease_acquire, 1);
    setFn(ctx, sys_lease, "release", nema_lease_release, 1);

    JSValue sys_tasks = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, sys, "tasks", sys_tasks);
    setFn(ctx, sys_tasks, "submit", nema_tasks_submit, 2);
    setFn(ctx, sys_tasks, "timeout", nema_tasks_timeout, 2);
    setFn(ctx, sys_tasks, "interval", nema_tasks_interval, 2);
    setFn(ctx, sys_tasks, "cancel", nema_tasks_cancel, 1);

    JSValue wallet = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, nema, "wallet", wallet);
    setFn(ctx, wallet, "networks", nema_wallet_networks, 0);
    setFn(ctx, wallet, "ready", nema_wallet_ready, 0);
    setFn(ctx, wallet, "address", nema_wallet_address, 2);
    setFn(ctx, wallet, "signMessage", nema_wallet_sign_message, 3);
    setFn(ctx, wallet, "signTransaction", nema_wallet_sign_transaction, 3);

    JSValue wifi = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, nema, "wifi", wifi);
    JSValue wifi_radio = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, wifi, "radio", wifi_radio);
    setFn(ctx, wifi_radio, "scan", nema_radio_scan, 0);
    setFn(ctx, wifi_radio, "monitorOpen", nema_radio_monitor_open, 1);
    setFn(ctx, wifi_radio, "monitorRead", nema_radio_monitor_read, 1);
    setFn(ctx, wifi_radio, "monitorClose", nema_radio_monitor_close, 0);
    setFn(ctx, wifi_radio, "inject", nema_radio_inject, 2);

    // device.name + device.caps (static properties)
    JS_SetPropertyStr(ctx, sys_device, "name", JS_NewString(ctx, host->device_name().c_str()));
    {
        const auto& cl = host->device_caps();
        JSValue arr = JS_NewArray(ctx);
        for (uint32_t i = 0; i < cl.size(); i++)
            JS_SetPropertyUint32(ctx, arr, i, JS_NewString(ctx, cl[i].c_str()));
        JS_SetPropertyStr(ctx, sys_device, "caps", arr);
    }

    JS_SetPropertyStr(ctx, g, "nema", nema);
    JS_FreeValue(ctx, g);
}
