// tools/idl/emit/parity.ts — Generate docs/api/parity.md coverage matrix.
// Tracks: host C++, QuickJS binding, WASM C header, JS .d.ts, docs, host impl.

import type { PidlAst } from "../ast";

export function emitParity(ast: PidlAst): string {
  const lines: string[] = [];

  lines.push("# Nema System API — Parity Matrix");
  lines.push("");
  lines.push("> Auto-generated from `api/build/nema-api.json`. Do not edit.");
  lines.push("> Host API version: `1.0`");
  lines.push("");

  // Collect all interface::function pairs
  interface Row {
    iface: string;
    fn: string;
    blocking: boolean;
  }
  const rows: Row[] = [];
  for (const pkg of ast.packages) {
    for (const iface of pkg.interfaces) {
      for (const fn of iface.functions) {
        rows.push({
          iface: `${pkg.name}/${iface.name}`,
          fn: fn.name,
          blocking: fn.annotations.blocking,
        });
      }
    }
  }

  lines.push("## Coverage");
  lines.push("");
  lines.push(`**Total functions:** ${rows.length}`);
  lines.push("");
  lines.push("| Interface | Function | Host C++ | QuickJS | WASM .h | JS .d.ts | Docs | Impl |");
  lines.push("|---|---|---|---|---|---|---|---|");

  for (const row of rows) {
    // Host C++: generated by host_cpp emitter (Phase 2)
    const hostCpp = "—";
    // QuickJS: generated by quickjs emitter (Phase 2)
    const quickjs = "—";
    // WASM .h: generated by wasm_h emitter (Phase 3)
    const wasmH = "—";
    // JS .d.ts: generated by dts emitter (Phase 3)
    const dts = "—";
    // Docs: always ✅ since docs emitter runs
    const docs = "✅";
    // Impl: hand-written in nema_host_impl.cpp (Phase 2)
    const impl = "—";

    const flags = row.blocking ? " 🔒" : "";
    lines.push(`| \`${row.iface}\` | \`${row.fn}\`${flags} | ${hostCpp} | ${quickjs} | ${wasmH} | ${dts} | ${docs} | ${impl} |`);
  }

  lines.push("");

  lines.push("## Legend");
  lines.push("");
  lines.push("| Symbol | Meaning |");
  lines.push("|---|---|");
  lines.push("| ✅ | Generated / implemented |");
  lines.push("| — | Not yet generated (pending phase) |");
  lines.push("| 🔒 | `@blocking` — must run on TaskRunner worker |");

  return lines.join("\n");
}
