#!/usr/bin/env bun
// tools/idl/gen.ts — Nema SDK binding generator (Plan 49).
//
// Reads api/build/nema-api.json (from Plan 48 parser) and emits:
//   Phase 1: docs/api/*.md, docs/api/parity.md
//   Phase 2: generated/host/nema_api.gen.h, generated/host/nema_api_quickjs.gen.cpp
//   Phase 3: generated/sdk/nema.d.ts, generated/sdk/nema.h
//
// Usage:
//   bun run tools/idl/gen.ts --ast api/build/nema-api.json --out generated
//   bun run tools/idl/gen.ts --ast api/build/nema-api.json --out generated --check

import { readFile, mkdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { existsSync } from "node:fs";
import type { PidlAst } from "../ast";
import { emitDocs } from "./emit/docs";
import { emitParity } from "./emit/parity";
import { emitHostCpp } from "./emit/host_cpp";
import { emitQuickJS } from "./emit/quickjs";
import { emitDts } from "./emit/dts";
import { emitWasmC } from "./emit/wasm_c";
import { emitPlpTs } from "./emit/plp_ts";

// ── CLI ───────────────────────────────────────────────────────────────────

interface Args {
  ast: string;
  out: string;
  check: boolean;
}

function parseArgs(): Args {
  const args: Args = { ast: "", out: "generated", check: false };
  for (let i = 2; i < process.argv.length; i++) {
    if (process.argv[i] === "--ast") args.ast = process.argv[++i];
    else if (process.argv[i] === "--out") args.out = process.argv[++i];
    else if (process.argv[i] === "--check") args.check = true;
  }
  return args;
}

// ── File writer ────────────────────────────────────────────────────────────

async function writeIfChanged(path: string, content: string): Promise<boolean> {
  const old = existsSync(path) ? await readFile(path, "utf-8") : "";
  if (old === content) return false;
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
  return true;
}

async function writeGenerated(name: string, content: string, outDir: string): Promise<boolean> {
  const path = join(outDir, name);
  const stamp = `// @generated from api/build/nema-api.json — DO NOT EDIT\n// Generated by packages/idl/src/gen.ts (Plan 49)\n\n`;
  return writeIfChanged(path, stamp + content);
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs();

  if (!args.ast) {
    console.error("Usage: gen.ts --ast <nema-api.json> --out <dir> [--check]");
    process.exit(1);
  }

  const ast: PidlAst = JSON.parse(await readFile(args.ast, "utf-8"));

  let changes = 0;

  // Phase 1: Docs + parity
  const docsDir = join(args.out, "docs", "api");
  const docs = emitDocs(ast);
  for (const [name, content] of docs) {
    const path = join(docsDir, name);
    if (await writeIfChanged(path, content)) {
      console.log(`  docs/api/${name}`);
      changes++;
    }
  }

  const parity = emitParity(ast);
  if (await writeIfChanged(join(docsDir, "parity.md"), parity)) {
    console.log("  docs/api/parity.md");
    changes++;
  }

  // Phase 2: Host C++
  if (await writeGenerated("host/nema_api.gen.h", emitHostCpp(ast), args.out)) {
    console.log("  generated/host/nema_api.gen.h");
    changes++;
  }
  if (await writeGenerated("host/nema_api_quickjs.gen.cpp", emitQuickJS(ast), args.out)) {
    console.log("  generated/host/nema_api_quickjs.gen.cpp");
    changes++;
  }

  // Phase 3: SDK .d.ts + WASM C header
  if (await writeGenerated("sdk/nema.d.ts", emitDts(ast), args.out)) {
    console.log("  generated/sdk/nema.d.ts");
    changes++;
  }
  if (await writeGenerated("sdk/nema.h", emitWasmC(ast), args.out)) {
    console.log("  generated/sdk/nema.h");
    changes++;
  }

  // Phase 4: PLP types for @palanu/link (Plan 77)
  // Written directly into the link package src so it's importable.
  const plpPath = join("packages", "link", "src", "types-generated.ts");
  const plpContent = `// @generated from api/build/nema-api.json — DO NOT EDIT\n// Generated by packages/idl/src/gen.ts (Plan 77)\n\n` + emitPlpTs(ast);
  if (await writeIfChanged(plpPath, plpContent)) {
    console.log("  packages/link/src/types-generated.ts");
    changes++;
  }

  if (args.check && changes > 0) {
    console.error(`\n❌ ${changes} file(s) are stale. Run gen.ts without --check to regenerate.`);
    process.exit(1);
  }

  const verb = args.check ? "would update" : "updated";
  console.log(`\n  ✓ ${changes} file(s) ${verb}\n`);
}

main().catch((e) => {
  console.error(`\n❌ ${e.message}`);
  process.exit(1);
});
