// @generated from api/build/nema-api.json — DO NOT EDIT
// Generated by packages/idl/src/gen.ts (Plan 49)

#ifndef NEMA_H
#define NEMA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Nema System API — WASM import declarations (Plan 49/57).
 * These are provided by the host (WasmRuntime) as WASM imports.
 * Include this header in WASM app C/C++ sources.
 * DO NOT call these from host (C++) code; use HostApi instead. */

/* ── aether:ui ─────────────────────────────────────────── */
/* Begin a container view (row or column flex direction). direction: "row" or "col" */
extern int32_t aether_ui__view_view_begin(const char* direction);
/* End the current container. Children added after this go to the parent. */
extern void aether_ui__view_view_end(void);
/* Simple text label (body style). */
extern int32_t aether_ui__text_label(const char* content);
/* Styled text. variant ∈ {"title", "subtitle", "body", "caption"}. */
extern int32_t aether_ui__text_styled(const char* content, const char* variant);
/* Pressable button with label and on-press callback handle. */
extern int32_t aether_ui__interactive_button(const char* label, int32_t on_press);
/* Begin a vertical scroll region. Returns handle for content children. */
extern int32_t aether_ui__scroll_scroll_begin(void);
/* End the scroll region. */
extern void aether_ui__scroll_scroll_end(void);

/* ── nema:bt ───────────────────────────────────────────── */
/* Whether the BLE controller is enabled. */
extern int32_t nema_bt__ble_enable(void);
/* Stop the BLE controller. */
extern void nema_bt__ble_disable(void);
/* Whether BLE is active and advertising/connected. */
extern uint32_t nema_bt__ble_is_enabled(void);

/* ── nema:input ────────────────────────────────────────── */
/* Get the hardware-specific hint label for an Action. */
extern const char* nema_input__input_hint(const char* action);
/* List all supported actions on this device. */
extern int32_t nema_input__input_actions(void);

/* ── nema:media ────────────────────────────────────────── */
/* List available audio input devices. */
extern int32_t nema_media__audio_input_list(void);
/* List available audio output devices. */
extern int32_t nema_media__audio_output_list(void);
/* List available camera devices. */
extern int32_t nema_media__camera_list(void);
/* Capture a frame from the default camera. @blocking — runs on worker. */
extern int32_t nema_media__camera_capture(const char** out_value);

/* ── nema:net ──────────────────────────────────────────── */
/* HTTPS GET. Returns the response or an error string on transport failure. */
extern int32_t nema_net__http_get(const char* url, int32_t* out_value);
/* HTTPS POST with a body and Content-Type header. */
extern int32_t nema_net__http_post(const char* url, const char* body, const char* content_type, int32_t* out_value);
/* Whether the device is currently connected to an AP. */
extern uint32_t nema_net__wifi_is_connected(void);
/* The SSID of the currently connected AP, or empty string. */
extern const char* nema_net__wifi_ssid(void);
/* The local IP address, or empty string. */
extern const char* nema_net__wifi_ip(void);
/* Start a Wi-Fi scan. @blocking — runs on worker. */
extern int32_t nema_net__wifi_scan(void);
/* Connect to an AP. */
extern int32_t nema_net__wifi_connect(const char* ssid, const char* password);
/* Disconnect from the current AP. */
extern void nema_net__wifi_disconnect(void);

/* ── nema:profile ──────────────────────────────────────── */
/* The device owner's display name (e.g. "Alice"). */
extern const char* nema_profile__profile_user_name(void);
/* The user-assigned device name (e.g. "My Palanu"). */
extern const char* nema_profile__profile_device_name(void);
/* Whether a password/PIN has been set. */
extern uint32_t nema_profile__profile_has_password(void);
/* Verify a password/PIN candidate. Uses constant-time comparison. Returns false if no password is set. */
extern uint32_t nema_profile__profile_verify_password(const char* input);

/* ── nema:storage ──────────────────────────────────────── */
/* Read a string value. Absent key → none. */
extern const char* nema_storage__kv_get(const char* key);
/* Write a string value (commits immediately). */
extern void nema_storage__kv_set(const char* key, const char* value);
/* Read a 64-bit int. Absent key → none. */
extern int64_t nema_storage__kv_get_int(const char* key);
/* Write a 64-bit int (commits immediately). */
extern void nema_storage__kv_set_int(const char* key, int64_t value);
/* Delete a key. Returns true if the key existed. */
extern uint32_t nema_storage__kv_remove(const char* key);
/* Read a file as a UTF-8 string. Returns none if the file does not exist. */
extern const char* nema_storage__fs_read_file(const char* name);
/* Write (create or overwrite) a file with UTF-8 content. */
extern uint32_t nema_storage__fs_write_file(const char* name, const char* data);
/* List files in the app's storage directory. */
extern int32_t nema_storage__fs_list_files(void);
/* Delete a file. Returns true if it existed. */
extern uint32_t nema_storage__fs_remove_file(const char* name);
/* Total bytes used across all files for this app (internal + SD). */
extern uint64_t nema_storage__fs_bytes_used(void);

/* ── nema:sys ──────────────────────────────────────────── */
/* Log a message at the given level. level ∈ {"trace", "debug", "info", "warn", "error", "fatal"} */
extern void nema_sys__log_log(const char* level, const char* tag, const char* msg);
/* Board/product name, e.g. "dev-board", "skyrizz-e32". */
extern const char* nema_sys__device_name(void);
/* All static capabilities this box was built with (Plan 42). */
extern int32_t nema_sys__device_caps(void);
/* Static: was this box built able to do X? */
extern uint32_t nema_sys__device_has(const char* cap);
/* Dynamic: is X up and usable right now? (Plan 42 liveness) */
extern uint32_t nema_sys__device_available(const char* cap);
/* Subscribe to an event name (or "*" for all). */
extern int32_t nema_sys__events_subscribe(const char* name, int32_t handler);
/* Remove a subscription by handle returned from subscribe. */
extern void nema_sys__events_unsubscribe(int32_t token);
/* Publish an event with optional string fields. */
extern void nema_sys__events_publish(const char* name, int32_t fields);
/* Submit a job to run on a worker thread; done() is called on the UI loop. @blocking marks that the job may block (http, wifi scan, ble enable). */
extern void nema_sys__tasks_submit(int32_t job, int32_t done);
/* Schedule a callback after delay milliseconds (one-shot). */
extern int32_t nema_sys__tasks_timeout(uint32_t ms, int32_t callback);
/* Schedule a repeating callback every interval milliseconds. */
extern int32_t nema_sys__tasks_interval(uint32_t ms, int32_t callback);
/* Cancel a pending timeout/interval by handle. */
extern void nema_sys__tasks_cancel(int32_t token);

#ifdef __cplusplus
}
#endif

#endif /* NEMA_H */
