// @generated from api/build/nema-api.json — DO NOT EDIT
// Generated by packages/idl/src/gen.ts (Plan 49)

declare namespace nema {
  namespace bt {
      // gated: bt.ble
    namespace ble {
      /** Whether the BLE controller is enabled. */
            enable(): Promise<{ ok: true; value: void } | { ok: false; error: string }>;
      /** Stop the BLE controller. */
            disable(): void;
      /** Whether BLE is active and advertising/connected. */
            is-enabled(): boolean;
    }

  }

  namespace input {
      // gated: input
    namespace input {
      /** Get the hardware-specific hint label for an Action. */
            hint(action: string): string;
      /** List all supported actions on this device. */
            actions(): string[];
    }

  }

  namespace media {
      // gated: audio.input
    namespace audio-input {
      /** List available audio input devices. */
            list(): string[];
    }

      // gated: audio.output
    namespace audio-output {
      /** List available audio output devices. */
            list(): string[];
    }

      // gated: camera
    namespace camera {
      /** List available camera devices. */
            list(): string[];
      /** Capture a frame from the default camera. @blocking — runs on worker. */
            capture(): Promise<{ ok: true; value: string } | { ok: false; error: string }>;
    }

  }

  namespace net {
      // gated: net.http
    namespace http {
      /** HTTPS GET. Returns the response or an error string on transport failure. */
            get(url: string): Promise<{ ok: true; value: http-response } | { ok: false; error: string }>;
      /** HTTPS POST with a body and Content-Type header. */
            post(url: string, body: string, content-type: string): Promise<{ ok: true; value: http-response } | { ok: false; error: string }>;
    }

      // gated: net.wifi
    namespace wifi {
      /** Whether the device is currently connected to an AP. */
            is-connected(): boolean;
      /** The SSID of the currently connected AP, or empty string. */
            ssid(): string;
      /** The local IP address, or empty string. */
            ip(): string;
      /** Start a Wi-Fi scan. @blocking — runs on worker. */
            scan(): Promise<wifi-ap[]>;
      /** Connect to an AP. */
            connect(ssid: string, password: string): Promise<{ ok: true; value: void } | { ok: false; error: string }>;
      /** Disconnect from the current AP. */
            disconnect(): void;
    }

  }

  namespace profile {
      // gated: profile
    namespace profile {
      /** The device owner's display name (e.g. "Alice"). */
            user-name(): string;
      /** The user-assigned device name (e.g. "My Palanu"). */
            device-name(): string;
      /** Whether a password/PIN has been set. */
            has-password(): boolean;
      /** Verify a password/PIN candidate. Uses constant-time comparison. Returns false if no password is set. */
            verify-password(input: string): boolean;
    }

  }

  namespace storage {
      // core
    namespace kv {
      /** Read a string value. Absent key → none. */
            get(key: string): string | null;
      /** Write a string value (commits immediately). */
            set(key: string, value: string): void;
      /** Read a 64-bit int. Absent key → none. */
            get-int(key: string): number | null;
      /** Write a 64-bit int (commits immediately). */
            set-int(key: string, value: number): void;
      /** Delete a key. Returns true if the key existed. */
            remove(key: string): boolean;
    }

  }

  namespace sys {
      // core
    namespace log {
      /** Log a message at the given level. level ∈ {"trace", "debug", "info", "warn", "error", "fatal"} */
            log(level: string, tag: string, msg: string): void;
    }

      // core
    namespace device {
      /** Board/product name, e.g. "dev-board", "skyrizz-e32". */
            name(): string;
      /** All static capabilities this box was built with (Plan 42). */
            caps(): string[];
      /** Static: was this box built able to do X? */
            has(cap: string): boolean;
      /** Dynamic: is X up and usable right now? (Plan 42 liveness) */
            available(cap: string): boolean;
    }

      // core
    namespace events {
      /** Subscribe to an event name (or "*" for all). */
            subscribe(name: string, handler: number): number;
      /** Remove a subscription by handle returned from subscribe. */
            unsubscribe(token: number): void;
      /** Publish an event with optional string fields. */
            publish(name: string, fields: field[]): void;
    }

      // core
    namespace tasks {
      /** Submit a job to run on a worker thread; done() is called on the UI loop. @blocking marks that the job may block (http, wifi scan, ble enable). */
            submit(job: number, done: number): void;
      /** Schedule a callback after delay milliseconds (one-shot). */
            timeout(ms: number, callback: number): number;
      /** Schedule a repeating callback every interval milliseconds. */
            interval(ms: number, callback: number): number;
      /** Cancel a pending timeout/interval by handle. */
            cancel(token: number): void;
    }

  }

  // ── Deprecated aliases (Plan 48 Fase 4) ──
  /** @deprecated Use nema.sys.log.log() */
  function log(level: string, tag: string, msg: string): void;
  /** @deprecated Use nema.sys.device */
  const device: typeof nema.sys.device;
  /** @deprecated Use nema.storage */
  namespace storage {
    /** @deprecated Use nema.storage.kv.get */
    function get(key: string): string | null;
    /** @deprecated Use nema.storage.kv.set */
    function set(key: string, value: string): void;
    /** @deprecated Use nema.storage.kv.remove */
    function remove(key: string): boolean;
  }
  /** @deprecated Use nema.net.http */
  namespace http {
    function get(url: string): Promise<{ status: number; body: string }>;
  }
}

declare type NemaResult<T, E> = { ok: true; value: T } | { ok: false; error: E };
