#!/usr/bin/env bun
// Embed built .kapp bundles into a C header so the firmware ships with built-in
// JS apps (the "Embedded" app store — Plan 37 Fase 5). Reads each templates/*/
// *.kapp (KAPP1\n<manifest>\n<js>) and emits firmware/.../embedded_apps.h.
import { resolve, join } from "path";
import { readdirSync, existsSync } from "fs";

const tplRoot = resolve(import.meta.dir, "../templates");
type App = { id: string; name: string; js: string };
const apps: App[] = [];

for (const dir of readdirSync(tplRoot)) {
  const d = join(tplRoot, dir);
  const manifestPath = join(d, "kapp.json");
  if (!existsSync(manifestPath)) continue;
  const manifest = JSON.parse(await Bun.file(manifestPath).text());
  const kappPath = join(d, `${manifest.id}.kapp`);
  if (!existsSync(kappPath)) { console.warn(`skip ${dir}: build it first (kairo-build)`); continue; }
  const raw = await Bun.file(kappPath).text();
  const nl1 = raw.indexOf("\n");
  const nl2 = raw.indexOf("\n", nl1 + 1);
  const js = raw.slice(nl2 + 1);
  if (js.includes(")KJS\"")) { console.error(`${dir}: js contains raw-string delimiter`); process.exit(1); }
  apps.push({ id: manifest.id, name: manifest.name, js });
}

const entries = apps.map(a =>
`    { "${a.id}", "${a.name}", R"KJS(
${a.js}
)KJS" },`).join("\n");

const header =
`// AUTO-GENERATED by packages/kairo-app-sdk/scripts/gen-embedded-apps.ts — do not edit.
// Built-in JS apps (the Embedded app store — Plan 37 Fase 5). Regenerate:
//   cd packages/kairo-app-sdk && bun bin/kairo-build.ts templates/counter && bun scripts/gen-embedded-apps.ts
#pragma once
namespace kairo {
struct EmbeddedApp { const char* id; const char* name; const char* js; };
inline const EmbeddedApp EMBEDDED_APPS[] = {
${entries}
};
inline constexpr int EMBEDDED_APP_COUNT = ${apps.length};
}
`;
const dest = resolve(import.meta.dir, "../../../firmware/core/include/kairo/apps/embedded_apps.h");
await Bun.write(dest, header);
console.log(`✓ embedded ${apps.length} app(s) → ${dest}: ${apps.map(a => a.name).join(", ")}`);
